// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package client

// Injectors from wire.go:

func InitializeClient(api Api, filename string) (*TreeClient, error) {
	treeClient := NewClient(api, filename)
	return treeClient, nil
}
